on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - .github/workflows/buildroot.yml
    types:
      - completed

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-kernel:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.kernel-diff.outputs.rebuild }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Diff kernel versions to check if buildroot needs to be rebuilded
        id: kernel-diff
        run: |
          cd buildroot
          if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]] || ! diff kernel-version-upstream.txt kernel-version-latest.txt; then
            echo "rebuild=yes" | tee -a "$GITHUB_OUTPUT"
          else
            echo "rebuild=no" | tee -a "$GITHUB_OUTPUT"
          fi
  packages:
    needs: check-kernel
    if: needs.check-kernel.outputs.rebuild == 'yes' || github.event_name == 'workflow_dispatch'
    env:
      IMAGE: packages
      IMAGE_TAG: latest
      IMAGE_FROM: buildroot
      IMAGE_FROM_TAG: latest
    runs-on: ubuntu-latest
    steps:
      - name: Login to ${{ env.REGISTRY }} as ${{ github.actor }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set SRC and DST env vars
        run: |
          echo "SRC=${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_FROM }}:${{ env.IMAGE_FROM_TAG }}" >> $GITHUB_ENV
          echo "DST=${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build from ${{ env.SRC }} and push the image to ${{ env.DST }}
        uses: docker/build-push-action@v5
        with:
          context: packages
          push: true
          tags: ${{ env.DST }}
          build-args: |
            SRC=${{ env.SRC }}
